//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_ticket.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetails
    {
        public int PaymentId { get; set; }
        public int ReservationID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int PaymentAmount { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual Reservations Reservations { get; set; }
    }
}
