//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_ticket.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int TicketId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DepartureTime { get; set; }
        public System.DateTime ArrivalTime { get; set; }
        public string DepartureStation { get; set; }
        public string ArrivalStation { get; set; }
        public int WagonNumber { get; set; }
        public int SeatNumber { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
