//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_ticket.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainTicks
    {
        public int Number_race { get; set; }
        public string Where_start { get; set; }
        public string Where_end { get; set; }
        public string When_data { get; set; }
        public string Type_van { get; set; }
    }
}
